/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { MutableRefObject, useEffect, useRef } from 'react'
import { useGLTF, useAnimations, PerspectiveCamera } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { useFrame } from '@react-three/fiber'

type GLTFResult = GLTF & {
  nodes: {
    [key: string]: THREE.Mesh
  }
  materials: {
    Waves: THREE.MeshPhysicalMaterial
  }
}

type ActionName = 'SceneRotate' | 'ConeAnim' | 'TorusAnim' | 'ParticlesAnim' | 'TubeAnim' | 'CubeAnim'
type GLTFActions = Record<ActionName, THREE.AnimationAction>

export function Model({ 
    scroll, props 
}: { 
    scroll: MutableRefObject<number>, 
    // props: JSX.IntrinsicElements['group']
}) {
  const group = useRef<THREE.Group>(null)
  const { nodes, materials, animations } = useGLTF('/HomeScene.glb') as GLTFResult
  const { actions } = useAnimations<GLTFActions>(animations, group)

  useEffect(() => 
    void (
        actions['SceneRotate']!.play().paused = false,
        actions['ConeAnim']!.play().paused = false,
        actions['TorusAnim']!.play().paused = false,
        actions['TubeAnim']!.play().paused = false,
        actions['CubeAnim']!.play().paused = false,
        actions['ParticlesAnim']!.play().paused = false,
    ), [])

    useFrame((state) => {
        actions["SceneRotate"]!.time = THREE.MathUtils.lerp(actions["SceneRotate"]!.time, actions["SceneRotate"]!.getClip().duration * scroll.current, 0.05)
        // group.current?.children[0].children.forEach((child, index) => {
        //   // @ts-ignore
        //   child.material.color.lerp(color.set(hovered === child.name ? materialColor : "#202020"), hovered ? 0.1 : 0.05)
        //   const et = state.clock.elapsedTime
        //   child.position.y = Math.sin((et + index * 2000) / 2) * 1
        //   child.rotation.x = Math.sin((et + index * 2000) / 3) / 10
        //   child.rotation.y = Math.cos((et + index * 2000) / 2) / 10
        //   child.rotation.z = Math.sin((et + index * 2000) / 3) / 10
        // })
      })

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="HomeScene">
        <group name="Group" rotation={[-Math.PI / 2, 0, 0]} scale={0.001}>
          <group name="Model" scale={1000}>
            <group name="OverallParent" scale={0.25}>
              <mesh
                name="Torus"
                castShadow
                receiveShadow
                geometry={nodes.Torus.geometry}
                material={materials.Waves}
                position={[0, -38.803, 0]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={[0.15, 0.15, 0.105]}
              />
              <group name="_Cone" position={[39.663, 0, -7.314]}>
                <mesh
                  name="Cone"
                  castShadow
                  receiveShadow
                  geometry={nodes.Cone.geometry}
                  material={materials.Waves}
                  position={[0, 0, -0.536]}
                  rotation={[0, 0.262, 0]}
                  scale={0.193}
                />
              </group>
              <group name="_Cube" position={[-39.391, 0, -6]}>
                <mesh
                  name="Cube"
                  castShadow
                  receiveShadow
                  geometry={nodes.Cube.geometry}
                  material={materials.Waves}
                  scale={0.132}
                />
              </group>
              <group name="_Tube" position={[0, 44.39, 0]} rotation={[Math.PI / 2, 0, 0]}>
                <mesh
                  name="Tube"
                  castShadow
                  receiveShadow
                  geometry={nodes.Tube.geometry}
                  material={materials.Waves}
                  rotation={[-0.262, 0, 0]}
                  scale={0.119}
                />
              </group>
              <mesh
                name="Sphere"
                castShadow
                receiveShadow
                geometry={nodes.Sphere.geometry}
                material={materials.Waves}
                position={[0, 0, -4.176]}
                scale={0.092}
              />
              <group name="_Particles" position={[37.99, 13.664, -96.596]}>
                <mesh
                  name="Particle"
                  castShadow
                  receiveShadow
                  geometry={nodes.Particle.geometry}
                  material={materials.Waves}
                  position={[16.683, -17.656, 132.621]}
                  rotation={[-2.742, -0.732, -2.448]}
                  scale={0.052}
                />
                <mesh
                  name="Particle_1"
                  castShadow
                  receiveShadow
                  geometry={nodes.Particle_1.geometry}
                  material={materials.Waves}
                  position={[1.735, 41.957, 117.095]}
                  rotation={[0.441, 1.36, 0.185]}
                  scale={0.026}
                />
                <mesh
                  name="Particle_2"
                  castShadow
                  receiveShadow
                  geometry={nodes.Particle_2.geometry}
                  material={materials.Waves}
                  position={[-86.366, 4.233, 75.292]}
                  rotation={[-0.623, 0.98, 0.766]}
                  scale={0.036}
                />
                <mesh
                  name="Particle_3"
                  castShadow
                  receiveShadow
                  geometry={nodes.Particle_3.geometry}
                  material={materials.Waves}
                  position={[-60.521, -98.79, 147.591]}
                  rotation={[1.844, 1.206, -1.336]}
                  scale={0.024}
                />
                <mesh
                  name="Particle_4"
                  castShadow
                  receiveShadow
                  geometry={nodes.Particle_4.geometry}
                  material={materials.Waves}
                  position={[-54.957, 39.819, 95.482]}
                  rotation={[0.672, 0.745, -0.766]}
                  scale={0.048}
                />
                <mesh
                  name="Particle_5"
                  castShadow
                  receiveShadow
                  geometry={nodes.Particle_5.geometry}
                  material={materials.Waves}
                  position={[124.263, 58.167, 82.351]}
                  rotation={[0.026, 1.108, 1.271]}
                  scale={0.047}
                />
                <mesh
                  name="Particle_6"
                  castShadow
                  receiveShadow
                  geometry={nodes.Particle_6.geometry}
                  material={materials.Waves}
                  position={[-7.971, 25.325, 77.077]}
                  rotation={[2.453, 0.255, 3.091]}
                  scale={0.048}
                />
                <mesh
                  name="Particle_7"
                  castShadow
                  receiveShadow
                  geometry={nodes.Particle_7.geometry}
                  material={materials.Waves}
                  position={[-17.639, -18.885, 106.167]}
                  rotation={[0.472, 0.844, -0.095]}
                  scale={0.085}
                />
                <mesh
                  name="Particle_8"
                  castShadow
                  receiveShadow
                  geometry={nodes.Particle_8.geometry}
                  material={materials.Waves}
                  position={[-32.979, -75.633, 159.691]}
                  rotation={[-2.896, 1.355, 2.43]}
                  scale={0.068}
                />
                <mesh
                  name="Particle_9"
                  castShadow
                  receiveShadow
                  geometry={nodes.Particle_9.geometry}
                  material={materials.Waves}
                  position={[-99.497, -41.028, 111.212]}
                  rotation={[-2.61, 0.033, 2.064]}
                  scale={0.039}
                />
                <mesh
                  name="Particle_10"
                  castShadow
                  receiveShadow
                  geometry={nodes.Particle_10.geometry}
                  material={materials.Waves}
                  position={[-99.838, 0.904, 129.62]}
                  rotation={[0.6, 0.348, 0.029]}
                  scale={0.035}
                />
                <mesh
                  name="Particle_11"
                  castShadow
                  receiveShadow
                  geometry={nodes.Particle_11.geometry}
                  material={materials.Waves}
                  position={[26.272, -89.613, 164.32]}
                  rotation={[2.772, 1.177, 3.089]}
                  scale={0.048}
                />
                <mesh
                  name="Particle_12"
                  castShadow
                  receiveShadow
                  geometry={nodes.Particle_12.geometry}
                  material={materials.Waves}
                  position={[-14.306, -75.041, 4.034]}
                  rotation={[-2.212, 0.805, 1.134]}
                  scale={0.057}
                />
                <mesh
                  name="Particle_13"
                  castShadow
                  receiveShadow
                  geometry={nodes.Particle_13.geometry}
                  material={materials.Waves}
                  position={[-31.042, -49.886, 66.137]}
                  rotation={[-2.887, 0.205, 3.121]}
                  scale={0.069}
                />
                <mesh
                  name="Particle_14"
                  castShadow
                  receiveShadow
                  geometry={nodes.Particle_14.geometry}
                  material={materials.Waves}
                  position={[21.36, 95.276, 123.392]}
                  rotation={[-1.55, -0.89, 2.942]}
                  scale={0.063}
                />
                <mesh
                  name="Particle_15"
                  castShadow
                  receiveShadow
                  geometry={nodes.Particle_15.geometry}
                  material={materials.Waves}
                  position={[14.857, -7.26, 111.975]}
                  rotation={[-2.565, -0.427, 2.007]}
                  scale={0.03}
                />
                <mesh
                  name="Particle_16"
                  castShadow
                  receiveShadow
                  geometry={nodes.Particle_16.geometry}
                  material={materials.Waves}
                  position={[-124.665, -18.275, 136.463]}
                  rotation={[-3.123, -0.456, -2.985]}
                  scale={0.057}
                />
                <mesh
                  name="Particle_17"
                  castShadow
                  receiveShadow
                  geometry={nodes.Particle_17.geometry}
                  material={materials.Waves}
                  position={[12.086, -20.026, 124.754]}
                  rotation={[-3.128, 0.28, 2.451]}
                  scale={0.052}
                />
                <mesh
                  name="Particle_18"
                  castShadow
                  receiveShadow
                  geometry={nodes.Particle_18.geometry}
                  material={materials.Waves}
                  position={[-86.603, 15.056, 89.808]}
                  rotation={[-2.764, -1.285, -0.921]}
                  scale={0.045}
                />
                <mesh
                  name="Particle_19"
                  castShadow
                  receiveShadow
                  geometry={nodes.Particle_19.geometry}
                  material={materials.Waves}
                  position={[4.133, 79.544, 110.317]}
                  rotation={[1.716, -1.301, 1.89]}
                  scale={0.054}
                />
                <mesh
                  name="Particle_20"
                  castShadow
                  receiveShadow
                  geometry={nodes.Particle_20.geometry}
                  material={materials.Waves}
                  position={[-44.212, -54.103, 54.879]}
                  rotation={[-0.563, -0.744, -0.01]}
                  scale={0.076}
                />
                <mesh
                  name="Particle_21"
                  castShadow
                  receiveShadow
                  geometry={nodes.Particle_21.geometry}
                  material={materials.Waves}
                  position={[21.399, 35.22, 62.474]}
                  rotation={[-1.048, -1.187, -1.538]}
                  scale={0.07}
                />
                <mesh
                  name="Particle_22"
                  castShadow
                  receiveShadow
                  geometry={nodes.Particle_22.geometry}
                  material={materials.Waves}
                  position={[-43.965, 39.249, 96.685]}
                  rotation={[-2.164, -0.807, -2.798]}
                  scale={0.036}
                />
                <mesh
                  name="Particle_23"
                  castShadow
                  receiveShadow
                  geometry={nodes.Particle_23.geometry}
                  material={materials.Waves}
                  position={[32.536, 12.113, 139.137]}
                  rotation={[-1.658, -0.908, -1.345]}
                  scale={0.061}
                />
                <mesh
                  name="Particle_24"
                  castShadow
                  receiveShadow
                  geometry={nodes.Particle_24.geometry}
                  material={materials.Waves}
                  position={[-13.273, -54.61, 82.04]}
                  rotation={[2.515, -1.007, 2.82]}
                  scale={0.012}
                />
                <mesh
                  name="Particle_25"
                  castShadow
                  receiveShadow
                  geometry={nodes.Particle_25.geometry}
                  material={materials.Waves}
                  position={[-73.462, -23.122, 107.232]}
                  rotation={[-2.77, -0.83, -2.439]}
                  scale={0.024}
                />
                <mesh
                  name="Particle_26"
                  castShadow
                  receiveShadow
                  geometry={nodes.Particle_26.geometry}
                  material={materials.Waves}
                  position={[30.508, -62.704, 120.799]}
                  rotation={[-0.704, -0.477, -0.525]}
                  scale={0.027}
                />
                <mesh
                  name="Particle_27"
                  castShadow
                  receiveShadow
                  geometry={nodes.Particle_27.geometry}
                  material={materials.Waves}
                  position={[-8.653, 25.878, 204.188]}
                  rotation={[0.342, -0.255, -0.834]}
                  scale={0.072}
                />
                <mesh
                  name="Particle_28"
                  castShadow
                  receiveShadow
                  geometry={nodes.Particle_28.geometry}
                  material={materials.Waves}
                  position={[-63.035, 8.088, 79.866]}
                  rotation={[-0.895, 0.545, -0.226]}
                  scale={0.021}
                />
                <mesh
                  name="Particle_29"
                  castShadow
                  receiveShadow
                  geometry={nodes.Particle_29.geometry}
                  material={materials.Waves}
                  position={[-51.914, 4.932, 68.293]}
                  rotation={[1.699, -0.856, 1.403]}
                  scale={0.031}
                />
                <mesh
                  name="Particle_30"
                  castShadow
                  receiveShadow
                  geometry={nodes.Particle_30.geometry}
                  material={materials.Waves}
                  position={[47.951, 46.237, 107.653]}
                  rotation={[0.192, -0.566, -0.692]}
                  scale={0.042}
                />
                <mesh
                  name="Particle_31"
                  castShadow
                  receiveShadow
                  geometry={nodes.Particle_31.geometry}
                  material={materials.Waves}
                  position={[-24.369, -15.554, 190.295]}
                  rotation={[-1.213, 0.327, 1.033]}
                  scale={0.083}
                />
              </group>
            </group>
          </group>
          <PerspectiveCamera
            name="Camera"
            makeDefault
            far={800}
            near={1}
            fov={60}
            position={[0.106, -20760.628, 0.481]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={1000}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/HomeScene.glb')